apiVersion: v1
kind: ConfigMap
metadata:
  name: dd-agent-confd
  namespace: fargate
data:
  app-java.yaml: |-
    logs:
      - type: file
        path: /var/log/app-java.log
        service: app-java
        source: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
  namespace: fargate
  labels:
    app.kubernetes.io/name: app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-java
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-java
    spec:
      serviceAccountName: datadog-agent
      containers:
        - name: app-java
          image: yaalexf/app-java
          env:
            - name: DD_SERVICE_NAME
              value: app-java
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
            - name: DD_JDBC_ANALYTICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_PROFILING_APIKEY
              valueFrom:
                secretKeyRef:
                  name: dd
                  key: api-key
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - name: logs
              mountPath: /var/log
        - image: datadog/agent
          name: datadog-agent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dd
                  key: api-key
            - name: DD_TAGS
              value: "env:eks"
            - name: DD_EKS_FARGATE
              value: "true"
            - name: DD_KUBERNETES_KUBELET_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_LOGS_ENABLED
              value: "true"
          volumeMounts:
            - name: dd-confd
              mountPath: /conf.d
            - name: logs
              mountPath: /var/log
      volumes:
        - name: logs
          emptyDir: {}
        - name: dd-confd
          configMap:
            name: dd-agent-confd
---
apiVersion: v1
kind: Service
metadata:
  name: app-java
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  selector:
    app.kubernetes.io/name: app-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
